# -*- coding: utf-8 -*-
"""space_separated_list_vibrio_cholerae.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RaNh1mLSpDlppIRWAgkC5ZuxQBaqNcbv

Exercise Break: 

Return a space-separated list of starting positions (in increasing order) where CTTGATCAT appears as a substring in the Vibrio cholerae genome.
"""

import requests

def find_initial_position_pattern(genome, pattern):
  for index in range(0, len(genome)):
      current_str = genome[index: index + len(pattern)]
      if current_str == pattern:
        print(index, end=" ")

def get_vibrio_cholerae_genome():  
  url_vibrio_cholerae = "https://raw.githubusercontent.com/ovvesley/bioinformatics/master/genomes/Vibrio_cholerae.txt"  
  genome_vibrio_cholerae = "" 
  try:
      r = requests.get(url_vibrio_cholerae)
      genome_vibrio_cholerae = r.text
      return genome_vibrio_cholerae
  except requests.exceptions.HTTPError as e:
      print (e.response.text)
      return ""

PATTERN = "CTTGATCAT" 
genome_vibrio_cholerae = get_vibrio_cholerae_genome()
find_initial_position_pattern(genome_vibrio_cholerae, PATTERN)

